### ISSUE TITLE
Add link to documentation on GitHub landing page

### ISSUE THREAD

**Issue by Bisaloo** [KnowledgeEdgeAI/PETs_for_Public_Health_Challenge#1]
It would helpful if the documentation website (https://pets-for-public-health-challenge.readthedocs.io/en/latest/) was more easily discoverable.

It could linked to from:

- the README
- the GitHub repository metadata, as described in https://stackoverflow.com/a/68162882/4439357.

**Comment by manandraj20** [comment]
done!
