### ISSUE TITLE
Add test dataset for tests

### ISSUE THREAD

**Issue by Bisaloo** [KnowledgeEdgeAI/PETs_for_Public_Health_Challenge#2]
Currently, it is not possible for an external contributors to run your tests because it relies on data that is not provided and linked from an hardcoded location on your machine:

https://github.com/KnowledgeEdgeAI/PETs_for_Public_Health_Challenge/blob/9172dd99a5fd6b40e087793eff4c57e78e6ed028/tests/test.py#L16

Even across the maintainers of this repo, this leads to necessary repeated changes:

https://github.com/KnowledgeEdgeAI/PETs_for_Public_Health_Challenge/commit/a1ffcae257da37b34fb5d1d482acd4b7d47e519f#diff-002b17638e4a840ab803fb150dddd393a637a14314ed5c395a048192850b2603L16

A more robust approach would be to create a smaller test dataset that would be included in this repo.

**Comment by Bisaloo** [comment]
I'm happy to submit a PR for this issue if that'd be helpful. Please let me know.

**Comment by manandraj20** [comment]
yes @Bisaloo. Thanks for offering! A PR would definitely be helpful. Feel free to submit one, and let us know if you need any further details or context on the issue.
