### ISSUE TITLE
Use a testing framework

### ISSUE THREAD

**Issue by Bisaloo** [KnowledgeEdgeAI/PETs_for_Public_Health_Challenge#4]
The current script in `tests/` only prints results and will not error if an unexpected return value is returned.

A recommended practice is to use a test framework and test outputs against specific assertions. If the assertions are not verified, an error is returned, which provides a clearer signal that something went wrong.

Some background & practical info for writing tests and using a test framework: https://www.pyopensci.org/python-package-guide/tests/index.html

**Comment by Bisaloo** [comment]
I'm happy to submit a PR for this issue if that'd be helpful. Please let me know.

**Comment by manandraj20** [comment]
yes @Bisaloo Please go ahead! Let us know if you need any additional context, especially regarding the tests
